version: "3.7"
services:
    api:
        build: ./server
        ports:
            - "8080:80"
        env_file:
            - ./server/config.local.env

    web:
        build: ./client
        ports:
            - "8081:80"
        depends_on:
            - api
