version: "3.7"
services:
    api:
        build: ./server
        volumes:
            - "./server:/app"
        expose:
            - "8080"
        env_file:
            - ./config.local.env

    web:
        build: ./client
        volumes:
            - "./client:/app"
        expose:
            - "8081"
        depends_on:
            - api

    proxy:
        build: ./proxy
        ports:
            - "80:80"
        depends_on:
            - api
            - web
